var definition = {
  currentIteration: null,
  nextIteration: null,
  user: null,
  isRegistered: null,
  statistics: null,
  unvests: null,
  canUnvest: null,
  bcStateRequirements: null,
  airkeyBalance: null, 
  XPRBalance: null,
  bcUnstaking: null,
  vestedOptions: null,
  freeosBalance: null,
  bcAirkeyBalance: null,
  liquidFreeos: null,
  liquidOptions: null, 
  totalFreeos: null,
  stakeRequirement: null,
  userHasStaked: null,
  userStake: null,
  userClaimedAlready: null,
  userMeetsStakeRequirement: null,
  totalHolding: null,
  canClaim: null,
  isFreeosEnabled: null,
  reasonCannotClaim: null,

  accountName: null,
  isAuthenticated: null,
  accountType: null,
  isVerified: null,
  allIterations: null,
  unstakingIteration: null,

  currencies: null,
  unvestPercentage: null, 
  airclaimStatus: null, 
  currentPrice: null,
  targetPrice: null,
  announceObj: null,
  lockFactor: null,
  mintFeeMin: null,

  priceLabel: null,
  userHasVoted: null,
  airclaimStatus: null,

  surveyShare: null,
  voteShare: null,
  surveyClosesIn: null,
  surveyPeriodActive: null,
  surveyCompleted: null, 
  voteStartsIn: null, 
  voteClosesIn: null,
  votePeriodActive: null,
  voteCompleted: null, 
  ratifyStartsIn: null,
  ratifyCompleted:null, 
  ratifyShare:null, 
  ratifyPeriodActive: null,
  ratifyClosesIn: null,

  rewardsPrevious: null,
  rewardsCurrent: null,

  systemRow: null,
  dparametersTable: null,
  nextClaimIn: null,
  eligibleToClaim: null,
  nextActivity: null,

  surveyRecord: null,

  freeosContract: null,
  usdContract: null,
  xprContract: null
}
export default definition
