var definition = {
  currentIteration: null,
  nextIteration: null,
  user: null,
  isRegistered: null,
  statistics: null,
  unvests: null,
  canUnvest: null,
  bcStateRequirements: null,
  airkeyBalance: null, 
  XPRBalance: null,
  bcUnstaking: null,
  vestedOptions: null,
  freeosBalance: null,
  bcAirkeyBalance: null,
  liquidFreeos: null,
  liquidOptions: null, 
  totalFreeos: null,
  stakeRequirement: null,
  userHasStaked: null,
  userStake: null,
  userClaimedAlready: null,
  userMeetsStakeRequirement: null,
  totalHolding: null,
  canClaim: null,
  isFreeosEnabled: null,
  reasonCannotClaim: null,

  accountName: null,
  isAuthenticated: null,
  allIterations: null,
  unstakingIteration: null,

  currencyName: null,
  stakeCurrency: null,
  unvestPercentage: null, 
  airclaimStatus: null, 
  currentPrice: null,
  targetPrice: null
}
export default definition
