export const currentIteration = ({ currentIteration }) => currentIteration
export const nextIteration = ({ nextIteration }) => nextIteration
export const user = ({ user }) => user
export const isRegistered = ({ isRegistered }) => isRegistered
export const statistics = ({ statistics }) => statistics
export const unvests = ({ unvests }) => unvests
export const canUnvest = ({ canUnvest }) => canUnvest
export const bcStateRequirements = ({ bcStateRequirements }) => bcStateRequirements
export const XPRBalance = ({ XPRBalance }) => XPRBalance
export const bcUnstaking = ({ bcUnstaking }) => bcUnstaking
export const vestedOptions = ({ vestedOptions }) => vestedOptions
export const liquidFreeos = ({ liquidFreeos }) => liquidFreeos
export const airkeyBalance = ({ airkeyBalance }) => airkeyBalance
export const liquidOptions = ({ liquidOptions }) => liquidOptions
export const stakeRequirement = ({ stakeRequirement }) => stakeRequirement
export const userHasStaked = ({ userHasStaked }) => userHasStaked
export const userClaimedAlready = ({ userClaimedAlready }) => userClaimedAlready
export const userMeetsStakeRequirement = ({ userMeetsStakeRequirement }) => userMeetsStakeRequirement
export const totalFreeos = ({ totalFreeos }) => totalFreeos
export const canClaim = ({ canClaim }) => canClaim
export const isFreeosEnabled = ({ isFreeosEnabled }) => isFreeosEnabled
export const userStake = ({ userStake }) => userStake
export const reasonCannotClaim = ({ reasonCannotClaim }) => reasonCannotClaim

export const isAuthenticated = ({ isAuthenticated }) => isAuthenticated
export const accountName = ({ accountName }) => accountName
export const allIterations = ({ allIterations }) => allIterations
export const unstakingIteration = ({ unstakingIteration }) => unstakingIteration

export const stakeCurrency = ({ stakeCurrency }) => stakeCurrency
export const currencyName = ({ currencyName }) => currencyName
export const unvestPercentage = ({ unvestPercentage }) => unvestPercentage
export const airclaimStatus = ({ airclaimStatus }) => airclaimStatus
export const currentPrice = ({ currentPrice }) => currentPrice
export const targetPrice = ({ targetPrice }) => targetPrice